---

- name: Swarm Services Setup
  hosts: dockermanager
  remote_user: user
  become: True
  roles:
    - visualisation
    - docker_registry
    - docker_tickstack
  vars:
    priv_reg: myregistry.com:5000