---
# tasks file for docker_swarm

- name: debian | installing pre-reqs
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python3-setuptools
    state: present
    update_cache: yes
  register: result
  
- name: Debug | installing pre-reqs
  debug: var=result verbosity=1

- name: debian | adding docker apt-key
  apt_key:
    url: "{{ docker_debian_repo_url }}"
    id: "{{ docker_debian_repo_id }}"
    state: present
  register: result

- name: Debug | adding docker apt-key
  debug: var=result verbosity=1

- name: debian | adding docker repo
  apt_repository:
    repo: "{{ docker_debian_repo_repo }}"
    state: present
  register: result

- name: Debug | adding docker repo
  debug: var=result verbosity=1

- name: debian | installing docker
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: present
    update_cache: yes
  register: result

- name: Debug | installing docker
  debug: var=result verbosity=1

- name: users | adding docker users (for use without sudo)
  user:
    name: "{{ item }}"
    append: yes
    groups: docker
  with_items:
    - docker

- name: service | Ensuring Docker Service Is Started And Enabled On Boot
  service:
    name: docker
    state: started
    enabled: true

- name: Install docker-compose
  pip:
    name: docker-compose
    state: latest
  when: ansible_default_ipv4.address == swarm_manager_ip

- name: Docker | Swarm Initialisation
  include: swarm.yml