---
# tasks file for docker_swarm

- name: debian | installing pre-reqs
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present
    update_cache: yes
#  register: result
#  until: result is successful

- name: debian | adding docker apt-key
  apt_key:
    url: "{{ docker_debian_repo_url }}"
    id: "{{ docker_debian_repo_id }}"
    state: present
#  register: result
#  until: result is successful

- name: debian | adding docker repo
  apt_repository:
    repo: "{{ docker_debian_repo_repo }}"
    state: present
#  register: result
#  until: result is successful

- name: debian | installing docker
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: present
    update_cache: yes
#  register: result
#  until: result is successful

- name: users | adding docker users (for use without sudo)
  user:
    name: "{{ item }}"
    append: yes
    groups: docker
  with_items:
    - docker

- name: service | Ensuring Docker Service Is Started And Enabled On Boot
  service:
    name: docker
    state: started
    enabled: true

- name: Docker | Swarm Initialisation
  include: swarm.yml

