# Run locally with: ansible-playbook create_playbook.yml --connection=local

---
- hosts: localhost
  become: no
  vars:
    playbook_name: infrastructure
    location: /var/ansible/{{ playbook_name }}
    roles: ["docker_swarm", "docker_registry", "gitlab", "common"]
  

  tasks:
    - name: Check if the playbook already exists
      stat: path={{ location }}
      register: playbook_directory

    - name: Create playbook directory
      file: path={{ item }} state=directory
      when: playbook_directory.stat.exists == False
      with_items:
        - "{{ location }} "
        - "{{ location }}/group_vars"
        - "{{ location }}/roles"

    - name: Create playbook files
      file: path={{ item }} state=touch
      with_items:
        - "{{ location }}/group_vars/all"
        - "{{ location }}/{{ playbook_name }}.yml"
    
    - name: Create role + task directory
      file: path={{ item }} state=directory
      with_items:
        - 

    - name: Create handler directory for each role

    - name: Create template directory for each role

    - name: Create files directory for each role

    - name: Create vars directory for each role

    - name: Create meta directory for each role

    - name: Create task file for each role

    - name: Create handler file for each role
