---

- hosts: all
  gather_facts: False
  remote_user: user
  become: yes
  become_user: root
  become_method: su

  tasks:
    - name: Install Python 2
      raw: test -e /usr/python || (apt update && atp install -y python sudo && echo "user     ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/user && echo "Defaults 	insults" > /etc/sudoers.d/insults)

    - name: Fancy way of doing authorized_keys
      authorized_key: user=root
                      excusive=no
                      key="{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"