---
# tasks file for common

- name: COMMON | Install basic packages
  # package: name={{ item }} state=present
  # with_items:
  apt:
    name:
      - vim
      - htop
      - iftop
      - tmux
      - powerline
      - iotop
      - bmon
      - mc
    state: present
    update_cache: yes