---
# tasks file for common

- name: COMMON | Install basic packages
  package: name={{ item }} state=present
  with_items:
    - vim
    - htop
    - iftop
    - tmux
    - powerline
    - iotop
    - bmon
    - mc