---
- name: Docker-compose | Create directory
  file:
    path: /var/docker/docker_registry/
    state: directory

- name: Docker-compose | Copy file
  copy:
    src: /var/ansible/infrastructure/roles/docker_registry/files/Docker-compose.yml
    dest: /var/docker/docker_registry/Docker-compose.yml
    owner: root
    group: root
    mode: '0777'

- name: Deploy stack from a compose file
  docker_stack:
    state: present
    name: registry
    compose:
      - /var/docker/docker_registry/Docker-compose.yml