---
# tasks file for visualisation

- name: Swarm | Visualisation
  docker_swarm_service:
    name: visualisation
    image: bretfisher/visualizer
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.role == manager
    publish:
      - published_port: "8080"
        target_port: "8080"
        protocol: tcp